[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename' ] ]
        \ },
        \ 'component_function': {
        \   'modified': 'LightlineModified',
        \   'readonly': 'LightlineReadonly',
        \   'fugitive': 'LightlineFugitive',
        \   'filename': 'LightlineFilename',
        \   'fileformat': 'LightlineFileformat',
        \   'filetype': 'LightlineFiletype',
        \   'fileencoding': 'LightlineFileencoding',
        \   'mode': 'LightlineMode'
        \ }
        \ }


function! LightlineModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightlineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'unite' ? unite#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:p') ? expand('%:p') : '[No Name]') .
        \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction

function! LightlineFugitive()
  if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
    return fugitive#head()
  else
    return ''
  endif
endfunction

function! LightlineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightlineFiletype()
  return winwidth(0) > 70 ? (&filetype !=# '' ? &filetype : 'no ft') : ''
endfunction

function! LightlineFileencoding()
  return winwidth(0) > 70 ? (&fenc !=# '' ? &fenc : &enc) : ''
endfunction

function! LightlineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction
'''

[[plugins]] # Nerdtree
repo = 'scrooloose/nerdtree'
[[plugins]] # Nerdtree Tabs
repo = 'jistr/vim-nerdtree-tabs'

#React関連
[[plugins]] # JavaScriptのシンタックスハイライト
repo = 'pangloss/vim-javascript'
[[plugins]] # JSXのシンタックスハイライト
repo = 'maxmellon/vim-jsx-pretty'
[[plugins]] # JavaScript補完
repo = 'ternjs/tern_for_vim'
merged = 0

[[plugins]] # Rails
repo = 'scrooloose/nerdtree'

[[plugins]] # Ruby向けにendを自動挿入してくれる
repo = 'tpope/vim-endwise'

#[[plugins]] # コメントON/OFFを手軽に実行
#repo = 'tomtom/tcomment_vim'

[[plugins]] # インデントに色を付けて見やすくする
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # ログファイルを色づけしてくれる
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]] # 行末の半角スペースを可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # (などの自動補完
repo = 'Raimondi/delimitMate'

[[plugins]] # Git
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'gregsexton/gitv'

#[[plugins]] # DB
#repo = 'vim-scripts/dbext.vim'

[[plugins]] # htmlタグ対応ハイライト
repo = 'valloric/matchtagalways'


# Lang

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'plasticboy/vim-markdown'

[[plugins]] # Markdown
repo = 'kannokanno/previm'

[[plugins]] # Markdown
repo = 'tyru/open-browser.vim'

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]] #Vue.js
repo = 'posva/vim-vue'
on_ft = 'vue'

# Colors
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
hi Comment ctermfg=102
hi Visual  ctermbg=3
hi CursorLine ctermbg=238
'''

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'rizzatti/dash.vim'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'

# Elixir / Phoenix
[[plugins]]
repo = 'elixir-lang/vim-elixir'
#[[plugins]]
#repo = 'awetzel/elixir.nvim'
[[plugins]]
repo = 'slashmili/alchemist.vim'
[[plugins]]
repo = 'c-brenn/phoenix.vim'
[[plugins]] #dependencie phoenix.vim
repo = 'tpope/vim-projectionist'
#[[plugins]]
#repo = 'tpope/vim-surround'
#[[plugins]]
#repo = 'avdgaag/vim-phoenix'

[[plugins]]
repo = 'xolox/vim-misc'
[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']
hook_add = '''
    " # 現在のディレクトリ直下の .vimsessions/ を取得
    let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
    " # 存在すれば
    if isdirectory(s:local_session_directory)
      " # session保存ディレクトリをそのディレクトリの設定
      let g:session_directory = s:local_session_directory
      " # vimを辞める時に自動保存
      let g:session_autosave = 'yes'
      " # 引数なしでvimを起動した時にsession保存ディレクトリのdefault.vimを開く
      let g:session_autoload = 'yes'
      " # 1分間に1回自動保存
      let g:session_autosave_periodic = 1
    else
      " # デフォルトの保存ディレクトリを変更する(NeoVimの場合)
      let g:session_directory = '~/.config/nvim/sessions'
      let g:session_autosave = 'yes'
      let g:session_autoload = 'yes'
      let g:session_autosave_periodic = 1
    endif
    unlet s:local_session_directory
	'''


[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'junegunn/fzf'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
[[plugins]]
repo = 'airblade/vim-gitgutter'

#slimシンタックスハイライト
[[plugins]]
repo = 'slim-template/vim-slim'
